/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        headingsSize: '24px',
      },
      colors:{
        primary:'#1976d2',
        anchor_base: '#1976d2',
       primary_base:' #1976d2',
      secondary_base: '#424242',
        accent_base: '#82b1ff',
        error_base: '#ff5252',
        info_base: '#2196f3',
        success_base: '#4caf50',
        warning_base: '#fb8c00',
        bg_black_base: '#1c1d1f',
        bg_true_black_base: '#000000',
        bg_white_base: '#ffffff',
        bg_background_base: '#ffffff',
        bg_raised_base: '#ffffff',
        bg_overlay_60_base: '#000099',
        bg_overlay_20_base: '#000033',
        bg_overlay_5_base: '#00000d',
        bg_neutral_a_base: '#f8f9fc',
        bg_neutral_b_base: '#f2f3f6',
        bg_neutral_c_base: '#e9ebee',
        bg_neutral_d_base: '#dadcde',
        bg_neutral_tonal_base: '#f2f3f6',
        bg_inverted_a_base: '#1c1d1f',
        bg_inverted_b_base: '#3c3e40',
        bg_inverted_c_base: '#5b5c5f',
        bg_inverted_d_base: '#6f7072',
        bg_inverted_tonal_base: '#f2f3f6',
        bg_success_a_base: '#1ea362',
        bg_success_b_base: '#4bb581',
        bg_success_c_base: '#b9e2ce',
        bg_success_d_base: '#157446',
        bg_success_tonal_base: '#e9f6ef',
        bg_brand_a_base: '#0072ff',
        bg_brand_b_base: '#338eff',
        bg_brand_c_base: '#b0d3ff',
        bg_brand_d_base: '#0051b5',
        bg_brand_tonal_base: '#e6f1ff',
        bg_error_a_base: '#d4394d',
        bg_error_b_base: '#dd6171',
        bg_error_c_base: '#f2c2c8',
        bg_error_d_base: '#972837',
        bg_error_tonal_base: '#fbebed',
        bg_warning_a_base: '#e06e16',
        bg_warning_b_base: '#e68b45',
        bg_warning_c_base: '#f5d2b7',
        bg_warning_d_base: '#9f4e10',
        bg_warning_tonal_base: '#fcf1e8',
        bg_brandsec_a_base: '#00b4e8',
        bg_brandsec_b_base: '#54d9ff',
        bg_brandsec_c_base: '#b0edff',
        bg_brandsec_d_base: '#008db5',
        bg_brandsec_tonal_base: '#e6f9ff',
        bg_teal_a_base: '#92c2cf',
        bg_teal_b_base: '#a8ced9',
        bg_teal_c_base: '#ddecf0',
        bg_teal_d_base: '#688a93',
        bg_primary_base: '#f8f9fc',
        bg_brandte_a_base: '#8758ff',
        bg_brandte_b_base: '#9f79ff',
        bg_brandte_c_base: '#9f79ff',
        bg_brandte_d_base: '#603eb5',
        bg_brandte_tonal_base: '#f3eeff',
        txt_de_primary_base: '#1c1d1f',
        txt_de_secondary_base: '#5b5c5f',
        txt_de_tertiary_base: '#97989b',
        txt_de_disabled_base: '#dadcde',
        txt_in_primary_base: '#f8f9fc',
        txt_in_secondary_base: '#e9ebee',
        txt_in_tertiary_base: '#b7b8bb',
        txt_in_disabled_base: '#6f7072',
        txt_white_base: '#ffffff',
        txt_success_base: '#1ea362',
        txt_error_base: '#d4394d',
        txt_warning_base: '#e06e16',
        txt_brand_base: '#0072ff',
        txt_brand_sec_base: '#00b4e8',
        txt_brand_te_base: '#7b50e8',
        icn_de_primary_base: '#1c1d1f',
        icn_de_secondary_base: '#5b5c5f',
        icn_de_tertiary_base: '#97989b',
        icn_de_disabled_base: '#dadcde',
        icn_in_primary_base: '#f8f9fc',
        icn_in_secondary_base: '#e9ebee',
        icn_in_tertiary_base: '#b7b8bb',
        icn_in_disabled_base: '#6f7072',
        icn_success_base: '#1ea362',
        icn_error_base: '#d4394d',
        icn_warning_base: '#e06e16',
        icn_brand_base: '#0072ff',
        icn_brand_sec_base: '#00b4e8',
        icn_brand_te_base: '#7b50e8',
        icn_white_base: '#ffffff',
        oln_de_primary_base: '#1c1d1f',
        oln_de_secondary_base: '#b7b8bb',
        oln_de_tertiary_base: '#dadcde',
        oln_de_disabled_base: '#e9ebee',
        oln_in_primary_base: '#f8f9fc',
        oln_in_secondary_base: '#97989b',
        oln_in_tertiary_base: '#6f7072',
        oln_in_disabled_base: '#3c3e40',
        oln_success_base: '#1ea362',
        oln_error_base: '#d4394d',
        oln_warning_base: '#e06e16',
        oln_brand_base: '#0072ff',
        oln_brand_sec_base: '#00b4e8',
        oln_brand_te_base: '#8758ff',
        oln_white_base: '#ffffff'
      },
      container:{
        center:true,
        padding:'1rem'
      },
      fontFamily:{
        IRANSansXBlack:"'IRANSansXBlack','serif'",
        IRANSansXBold:"'IRANSansXBold','serif'",
        IRANSansXDemiBold:"'IRANSansXDemiBold','serif'",
        IRANSansXExtraBold:"'IRANSansXExtraBold','serif'",
        IRANSansXLight:"'IRANSansXLight','serif'",
        IRANSansXMedium:"'IRANSansXMedium','serif'",
        IRANSansXRegular:"'IRANSansXRegular','serif'",
        IRANSansXThin:"'IRANSansXThin','serif'",
        IRANSansXUltraLight:"'IRANSansXUltraLight','serif'",
        BNazanin:"'BNazanin','serif'",
        NasimB:"'NasimB','serif'",
      }
    },
    lineHeight: {
      'headings': '40px',
    },

  },
  plugins: [],
}

